day16/urls.py
from django.contrib import admin
from django.urls import path
from app.views import depart, prety, user, admin, account, task, order, chart, upload
urlpatterns = [
    # path('admin/', admin.site.urls),
    # path("/",views.login)
    path("depart/list/",depart.depart_list),
    path("depart/add/",depart.depart_add),
    path("depart/delete/",depart.depart_delete),
    path("depart/<int:nid>/edit/",depart.depart_edit),

    path("user/list/",user.user_list),
    path("user/add/",user.user_add),
    path("user/model/form/add/",user.user_model_form_add),
    path("user/<int:nid>/edit/",user.user_edit),
    path("user/<int:nid>/delete/",user.delete_user),

    path("pretty/list/",prety.pretty_list),
    path("pretty/add/",prety.pretty_add),
    path("pretty/<int:nid>/delete/",prety.pretty_delete),
    path("pretty/<int:nid>/edit/",prety.pretty_edit),

    path("admin/list/",admin.admin_list),
    path("admin/add/",admin.admin_add),
    path("admin/<int:nid>/edit/",admin.admin_edit),
    path("admin/<int:nid>/reset/",admin.admin_reset),

    path("login/",account.login),
    path("logout/",account.logout),

    path("task/list/",task.task_list),
    path("task/ajax/",task.task_ajax),
    path("task/add/",task.task_add),


    #订单
    path("order/list/",order.order_list),
    path("order/add/",order.order_add),
    path("order/delete/",order.order_delete),
    path("order/edit/",order.order_edit),
    path("order/detail/",order.order_detail),

    path("chart/list/",chart.chart_list),
    path("chart/bar/",chart.chart_bar),
    path("chart/pie/",chart.chart_pie),
    path("chart/High/",chart.highchart),

#     文件上传
    path("upload/list/",upload.upload_list),



]

app/models.py
from django.db import models

# Create your models here.

class Admin(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name="用户名", max_length=64)
    password = models.CharField(verbose_name="密码", max_length=64)
    def __str__(self):
        return self.username
class Task(models.Model):
    """任务"""
    level_choice = (
        (1,"紧急"),
        (2,"重要"),
        (3,"临时"),
    )
    level = models.SmallIntegerField(verbose_name="程度",choices=level_choice,default=3)
    title = models.CharField(verbose_name="题目",max_length=64)
    detail = models.TextField(verbose_name="细节")
    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)
class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name="标题", max_length=32)
    def __str__(self):
        return self.title


class PretyNum(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    # 想要允许为空,null = True,  blank = True
    price = models.IntegerField(verbose_name="价格", default=0)

    level_choices = (
        (1, "1级别"),
        (2, "2级别"),
        (3, "3级别"),
        (4, "4级别"),
    )
    level = models.SmallIntegerField(verbose_name="级别",choices=level_choices, default=1)

    status_choices = (
        (1,"已经占用"),
        (2,"未占用")
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choices, default=2)




class UserInfo(models.Model):
    """ 员工表 """
    name = models.CharField(verbose_name="姓名", max_length=16)
    password = models.CharField(verbose_name="密码", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    # create_time = models.DateTimeField(verbose_name="入职时间")
    create_time = models.DateField(verbose_name="入职时间")
    #无约束的
    # depart_id = models.BigIntegerField(verbose_name="部门ID")
    # 1、 有约束
    #     to ，与这张表有关联
    #     to_filed, 表的一列
    # 2、 django自动
    #     写的depart
    #     生成数据列depart_id
    # 3、 部门表被删除
    #     3.1 级联删除
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete = models.CASCADE)
            # 3.2 置空
    # depart  = models.ForeignKey(to="Department", to_field="id", null=True, blank=True, on_delete=models.SET_NULL)

    #在django中做约束，对性别
    gender_choice = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choice)


class Order(models.Model):
    oid = models.CharField(verbose_name="订单号",max_length=64)
    title = models.CharField(verbose_name="商品名",max_length=64)
    price = models.CharField(verbose_name="价格",max_length=64)
    status_choice = (
        (1,"待支付"),
        (2,"已支付"),
    )
    status = models.SmallIntegerField(verbose_name="支付状态",choices=status_choice)
    admin = models.ForeignKey(verbose_name="管理员",to="Admin",on_delete=models.CASCADE)

app/views/login.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django import forms
from app import models
from app.utils.encrypt import md5



class LoginForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required=True#这个必须填写
        # widget=forms.Textarea(attrs={"class":"form-control"}),
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class":"form-control"}),
        required=True  # 这个必须填写
    )
    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

#这两个的效果是一样的
# class LoginModelForm(forms.ModelForm):
#     class Meta:
#         model = models.Admin
#         fields = ["username","password"]



def login(request):
    if request.method =="GET":
        form = LoginForm()
        return render(request, "login.html",{"form":form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)
        # {'username': '123', 'password': '456'}
        #去数据库校验  如果没有得到，返回为空
        #下面的这个会更加简介
        # admin_object = models.Admin.objects.filter(username=form.cleaned_data['username'], password = form.cleaned_data['password']).first()
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:# 用户名和密码错误
            form.add_error("password","用户名或者密码错误！！！")
            return render(request, "login.html", {"form": form})


        #用户名和密码正确
        request.session["info"] = {"id":admin_object.id, "name":admin_object.username}
        # return HttpResponse("提交成功")
        return redirect("/admin/list/")

    return render(request, "login.html", {"form": form})

app/templates/change.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form method="post" novalidate>
                <!--                不让浏览器进行校验-->
                {% csrf_token%}
                {% for field in form%}
                <div class="form-group">
                    <label> {{ field.label }}</label>
                    {{field}}
                    <span style="color:red;">{{field.errors.0}}</span>
                </div>
                {% endfor%}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/chart_high.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div id="m3" style="width: 100%;height:300px;">
    </div>
</div>
{% endblock %}
{% block js %}
<script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
<script src="https://code.hcharts.cn/highcharts.js"></script>
<script>
 var options = {
            chart: {
                type: 'bar'                          //指定图表的类型，默认是折线图（line）
            },
            title: {
                text: '我的第一个图表'                 // 标题
            },
            xAxis: {
                categories: ['苹果', '香蕉', '橙子']   // x 轴分类
            },
            yAxis: {
                title: {
                    text: '吃水果个数'                // y 轴标题
                }
            },
            series: [{                              // 数据列
                name: '小明',                        // 数据列名
                data: [1, 0, 4]                     // 数据
            }, {
                name: '小红',
                data: [5, 7, 3]
            }]
        };
        // 图表初始化函数
        var chart = Highcharts.chart('m3', options);

</script>
{% endblock %}

app/templates/depart_add.html
{% extends 'layout.html' %}

{% block content %}
   <div class="container">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">添加部门</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token%}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">部门</label>
                        <div class="col-sm-10">
                            <input name="part_name" type="text" class="form-control" placeholder="name">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">添加</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/depart_edit.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">修改用户</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token%}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">部门</label>
                        <div class="col-sm-10">
                            <input name="part_name" type="text" class="form-control" placeholder="name" value="{{title}}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">确定</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
{% endblock %}

app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static  'plugins/bootstrap/css/bootstrap.css'%}">
    <link rel="stylesheet" href="{% static  'plugins/font-awesome/css/font-awesome.css'%}">
    <link rel="stylesheet"
          href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.css' %}">

<!--自定义css-->
    {% block  css%}

    {% endblock %}


</head>
<body>

<nav class="navbar navbar-default">

    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">小即管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <li><a href="/admin/list">超级用户</a></li>
                <li><a href="/depart/list">部门管理</a></li>
                <li><a href="/user/list">用户管理</a></li>
                <li><a href="/pretty/list">靓号管理</a></li>
                <li><a href="/task/list">任务管理</a></li>
                <li><a href="/order/list">订单管理</a></li>
                <li><a href="/chart/list">数据统计</a></li>
                <li><a href="/chart/High">HighCharts</a></li>

            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        {{request.session.info.name}}
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li><a href="#">我的信息</a></li>
                        <li><a href="#"> 主食</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div>

        {% block content %}

        {% endblock%}

</div>


<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
<!--自定义js -->
    {% block  js %}

    {% endblock %}
</body>
</html>

app/templates/order_list.html
{% extends 'layout.html' %}

{% block content%}
<div class="container">
    <div>
        <!--        第一种-->
        <input type="button" value="新建订单1" class="bun btn-primary" data-toggle="modal" data-target="#myModal">
        <!--        第二种，直接通过id，连接两个id-->
        <input id="btnadd" type="button" value="新建订单2" class="bun btn-primary">
    </div>


    <div class="panel panel-default">
        <div class="panel-heading"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>订单列表</div>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th>订单号</th>
                <th>名称</th>
                <th>价格</th>
                <th>状态</th>
                <th>管理员</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in queryset %}
            <tr>
                <th>{{obj.id}}</th>
                <th>{{obj.oid}}</th>
                <td>{{obj.title}}</td>
                <td>{{obj.price}}</td>
                <td>{{obj.get_status_display}}</td>
                <td>{{obj.admin.username}}</td>
                <td>
                    <!--                    <a href="#" class="btn btn-primary btn-xs">编辑</a>-->
                    <input type="button" class="btn btn-primary btn-xs btn-edit" orderid="{{obj.id}}" value="编 辑">
                    <!--                    <a href="#" class="btn btn-danger btn-xs">删除</a>-->
                    <input orderid="{{obj.id}}" type="button" class="btn btn-danger btn-xs btn-delete" value="删 除">
                </td>
            </tr>
            {% endfor %}


            </tbody>
        </table>

    </div>

    <ul class="pagination">
        {{page_string}}
    </ul>


</div>


<!-- 新建/编辑订单，对话框 -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">新建</h4>
            </div>
            <div class="modal-body">
                <form id="formModel" novalidate>
                    <!--                不让浏览器进行校验-->
                    <div class="clearfix">
                        {% for field in form%}
                        <div class="col-xs-6">
                            <div class="form-group" style="position: relative; margin-top: 15px">
                                <label> {{ field.label }}</label>
                                {{field}}
                                <span class="error-smg" style="color:red; position: absolute"></span>
                            </div>
                        </div>
                        {% endfor%}
                    </div>
                    <!--                <button type="button" id="butadd" class="btn btn-default">提交</button>-->
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button id="bunSave" type="button" class="btn btn-primary">保存</button>
            </div>
        </div>
    </div>


</div>

<!--确定是否删除的弹出框-->
<div class="modal fade" id="myModaldelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <h4>是否确认删除？</h4>
            <p>所有的都要删除</p>
            <p style="text-align: right">
                <!--                如果点击的确定，那就需要把全局变量deleteid进行删除了-->
                <button id="confirmdelete" type="button" class="btn btn-danger">确认</button>

                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            </p>
        </div>
    </div>


</div>

<!--编辑的对话框-->
{% endblock %}
{% block js %}
<script type="text/javascript">
    var DELETE_ID;
    var EDIT_ID;
    $(function () {
        bindBtnAddEvent2();
        bindBtnSave();
        bindbtnDelete();
        bindConfirmDelete();
        bindEdit();
    })

    function bindEdit() {
        $(".btn-edit").click(function () {
            var currentID = $(this).attr("orderid");
            $.ajax({
                url: "/order/detail/",
                type: "get",
                data: {
                    uid: currentID
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {

                        //因为编辑的原因，所以需要在点击新建的时候，清空
                        $("#formModel")[0].reset();
                        EDIT_ID = currentID;

                        // console.log(res)
                        // alert("添加成功");

                        // <input type="text" name="title" maxlength="64" class="form-control" placeholder="商品名" required="" id="id_title">
                        // $("#id_title").text(data["title"]);
                        $.each(res.data,function (name,value){
                            $("#id_" + name).val(value)
                        })
                        // location.reload();
                        // 还需要修改对话框的标题
                        $("#myModalLabel").text("编辑");
                        //
                        // // alert("点击了编辑");
                        $("#myModal").modal('show');
                    } else {
                        alert(res.error);
                    }

                }
            })
            // $.ajax({
            //     url:"/order/edit/",
            //     type:"POST",
            //     data:{
            //         uid:currentID
            //     },
            //     dataType:"JSON",
            //     success:function (res){
            //         if(res.status){
            //             alert("添加成功");
            //             location.reload();
            //         }
            //
            //     }
            // })
        })

    }

    function bindConfirmDelete() {
        $("#confirmdelete").click(function () {
            $.ajax({
                url: '/order/delete/',
                type: "GET",
                data: {
                    uid: DELETE_ID
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        // alert("删除成功");
                        // 隐藏删除狂
                        // $("#myModaldelete").modal('hide');
                        // 全局变量修改
                        DELETE_ID = -1;

                        // //用js实现页面的刷新
                        location.reload();
                        //清空表单
                        // $("#formModel")[0].reset();
                        //
                        // //之前是显示，现在让他关闭
                        // $("#myModal").modal('hide');
                        // location.reload();

                    } else {
                        alert("删除失败!")
                    }


                }
            })


        })

    }

    function bindbtnDelete() {
        $(".btn-delete").click(function () {
            $("#myModaldelete").modal('show');

            //     当点击删除的时候，也需要获取id并给全局变量
            var uid = $(this).attr("orderid");
            console.log(uid)
            DELETE_ID = uid;
        })


    }

    function bindBtnAddEvent2() {
        $("#btnadd").click(function () {
            //因为编辑的原因，所以需要在点击新建的时候，清空
            $("#formModel")[0].reset();
            //
            EDIT_ID = false;

            // 设置对话框标题
            $("#myModalLabel").text("新建");
            $("#myModal").modal('show');
        })
    }

    function bindBtnSave() {
        $("#bunSave").click(function () {
            // alert("保存");
            // 点击之前把所有的error清空
            $(".error-smg").empty()
            if(EDIT_ID){
                //编辑
                 $.ajax({
                url: '/order/edit/' + '?uid=' + EDIT_ID,  // ->  /order/edit/?uid=xxx
                type: "post",
                data: $("#formModel").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        alert("更改成功");
                        //用js实现页面的刷新
                        // location.reload();
                        //清空表单
                        $("#formModel")[0].reset();

                        //之前是显示，现在让他关闭
                        $("#myModal").modal('hide');
                        location.reload();

                    } else {
                        if(res.tips){
                            alert(res.tips)
                        }else {
                             $.each(res.error, function (name, data) {
                            console.log(name, data);
                            $("#id_" + name).next().text(data[0])

                        })

                        }



                    }


                }
            })
            }else{
                //新建
                 $.ajax({
                url: '/order/add/',
                type: "post",
                data: $("#formModel").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        alert("添加成功");
                        //用js实现页面的刷新
                        // location.reload();
                        //清空表单
                        $("#formModel")[0].reset();

                        //之前是显示，现在让他关闭
                        $("#myModal").modal('hide');
                        location.reload();

                    } else {
                        $.each(res.error, function (name, data) {
                            console.log(name, data);
                            $("#id_" + name).next().text(data[0])

                        })
                    }


                }
            })
            }



        })
    }

</script>
{% endblock %}

app/templates/task_list.html
{% extends 'layout.html' %}


{% block content %}
<div class="container">
    <div class="panel panel-danger">
        <div class="panel-heading">
            <h3 class="panel-title">Panel title</h3>
        </div>
        <div class="panel-body">
            <form id="formadd" novalidate>
                <!--                不让浏览器进行校验-->
                <div class="clearfix">
                    {% for field in form%}
                    <div class="col-xs-6">
                        <div class="form-group" style="position: relative; margin-top: 15px">
                            <label> {{ field.label }}</label>
                            {{field}}
                            <span class="error-smg" style="color:red; position: absolute"></span>
                        </div>
                    </div>
                    {% endfor%}
                </div>

                <button type="button" id="butadd" class="btn btn-default">提交</button>

            </form>

        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>任务列表</div>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th> 标题</th>
                <th> 级别</th>
                <th>负责人</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in queryset %}
            <tr>
                <th>{{obj.id}}</th>
                <td>{{obj.title}}</td>
                <td>{{obj.get_level_display}}</td>
                <td>{{obj.user.username}}</td>

                <td>
                    <a href="/admin/{{obj.id}}/edit/" class="btn btn-primary btn-xs">编辑</a>

                    <a href="/depart/delete/?nid={{obj.id}}" class="btn btn-danger btn-xs">删除</a>

                </td>

            </tr>
            {% endfor %}


            </tbody>
        </table>

    </div>

    <ul class="pagination">
        {{page_string}}
    </ul>


    <div style="height: 1000px"></div>
    <hr>
    <h1>任务列表</h1>
    <h3>实例1</h3>
    <!--基于dom的方式绑定事件 onclick=xxx-->
    <input type="button" class="btn btn-primary" value="按钮1" onclick="clickme();">
    <!--基于jquery的方式绑定事件 -->
    <input id="btn2" type="button" class="btn btn-primary" value="按钮2">
    <!--将input框的数据提交到后台-->
    <input id="text1" type="text" placeholder="输入数据">
    <!--将input框的数据提交到后台 -->
    <input id="btn3" type="button" class="btn btn-primary" value="按钮3">


    <!--    如果输入框很多，用form 需要有name serialize-->
    <form id="form3">
        <input name="name" type="text" placeholder="姓名">
        <input name="age" type="text" placeholder="年龄">
        <input name="sex" type="text" placeholder="性别">
        <input name="more" type="text" placeholder="更多">
    </form>
    <input id="btn4" type="button" class="btn btn-primary" value="按钮4">

</div>

{% endblock %}

{% block js%}

<script type="text/javascript">

    <!--    利用jquery实现ajax-->
    $(function () {
        //页面加载完成之后代码自动执行
        bindBtn1Event();
        bindBtn2Event();
        bindBtn3Event();
        bindBtnAddEvent();
    })

    function bindBtn1Event() {
        $("#btn2").click(function () {
            $.ajax({
                url: '/task/ajax/',
                type: "get",
                // type: "post",
                data: {
                    n1: 123,
                    n2: 456
                },
                dataType: "JSON",
                success: function (res) {
                    console.log(res);
                    console.log(res.status);
                    console.log(res.data);
                }
            })

        })
    }

    function bindBtn2Event() {
        $("#btn3").click(function () {
            $.ajax({
                url: '/task/ajax/',
                type: "post",
                // type: "post",
                data: {
                    text: $("#text1").val()
                },
                dataType: "JSON",
                success: function (res) {
                    console.log(res);
                    console.log(res.status);
                    console.log(res.data);
                }
            })

        })
    }

    function bindBtn3Event() {
        $("#btn4").click(function () {
            $.ajax({
                url: '/task/ajax/',
                type: "post",
                // type: "post",
                data: $("#form3").serialize(),
                dataType: "JSON",
                success: function (res) {
                    console.log(res);
                    console.log(res.status);
                    console.log(res.data);
                }
            })

        })
    }

    function bindBtnAddEvent() {
        $("#butadd").click(function () {

            // 点击之前把所有的error清空
            $(".error-smg").empty()

            $.ajax({
                url: '/task/add/',
                type: "post",
                // type: "post",
                data: $("#formadd").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        alert("添加成功");
                        //用js实现页面的刷新
                        location.reload();
                    } else {
                        $.each(res.error, function (name, data) {
                            console.log(name, data);
                            $("#id_" + name).next().text(data[0])

                        })

                    }

                }
            })

        })
    }

    // 利用dom进行绑定
    function clickme() {
        // console.log("点击了我以下");
        $.ajax({
            url: '/task/ajax/',
            // type: "get",
            type: "post",
            data: {
                n1: 123,
                n2: 456
            },
            success: function (res) {
                console.log(res);
            }
        })
    }
</script>

{% endblock%}

app/templates/upload_list.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<div class="container">
  <form method="post" enctype="multipart/form-data">
 {% csrf_token%}
    <input type="text" name="username">
    <input type="file" name="avatar">
    <input type="submit" value="提交">

  </form>
  
</div>
{% endblock %}

app/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div style="margin-bottom: 10px">
        <a href="/user/add" class="btn btn-success" target="_blank">添加用户</a>
    </div>

    <div style="margin-bottom: 10px">
        <a href="/user/model/form/add" class="btn btn-success" target="_blank">添加用户(ModelForm)</a>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading"><span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>用户列表</div>
        <table class="table">
            <thead>
            <tr>
                <th>ID</th>
                <th> 姓名</th>
                <th>密码</th>
                <th>年龄</th>
                <th>账户余额</th>
                <th>入职时间</th>
                <th>部门</th>
                <th>性别</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>

            {% for obj in queryset%}
            <tr>
                <th>{{obj.id}}</th>
                <th>{{obj.name}}</th>
                <th>{{obj.password}}</th>
                <th>{{obj.age}}</th>
                <th>{{obj.account}}</th>
                <th>{{obj.create_time|date:"Y-m-d"}}</th>
                <th>{{obj.depart.title}}</th>
                <th>{{obj.get_gender_display}}</th>
                <th>
                    <a href="/user/{{obj.id}}/edit/" class="btn btn-primary btn-xs">编辑</a>
                    <a href="/user/{{obj.id}}/delete/" class="btn btn-danger btn-xs">删除</a>
                </th>

            </tr>

            {% endfor%}

            </tbody>
        </table>
    </div>
     <ul class="pagination">
        {{ page_string }}
    </ul>

</div>

{% endblock %}